name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # ブランチ名がmasterの場合は書き換えてください

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install, build, and upload with Astro
        uses: withastro/action@v3
        # リポジトリ名を含むURLにする場合は、path: my-blog のように指定が必要な場合があります

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
